@echo off
echo Starting Urban Elegance Website...
echo.
echo Starting PHP Development Server...
start /min cmd /c "C:\xampp\php\php.exe -S localhost:8000 -t ."
timeout /t 3 /nobreak >nul
echo Opening Urban Elegance website in browser...
start http://localhost:8000/index.html
echo.
echo Urban Elegance is running at: http://localhost:8000
echo Press any key to stop the server...
pause >nul